### ISSUE TITLE
Any way to play using include_bytes()?

### ISSUE THREAD

**Issue by jD91mZM2** [jeremyletang/ears#16]
It would be great if you could play bytes so you can play music using include_bytes(). Cheers!

**Comment by jeremyletang** [comment]
hey @legolord208, you should ask for this here: https://github.com/jhasse/ears, this fork is more maintained / up to date. I do not work anymore on ears here. cheers.

**Comment by jD91mZM2** [comment]
Oh - ok. Cheers!
